# Data Sources
NASA_SBDB_API: "https://ssd-api.jpl.nasa.gov/sbdb.api"
NASA_API_KEY: ""  # Set via environment variable NASA_API_KEY
NEOWISE_DATA_URL: "https://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-query"

# Account Information
NASA_ACCOUNT:
  email: ""  # Set via environment variable NASA_EMAIL
  account_id: ""  # Set via environment variable NASA_ACCOUNT_ID

# Model Configuration
MODEL_CONFIG:
  random_forest:
    n_estimators: 200
    max_depth: 15
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
  
  gradient_boosting:
    n_estimators: 150
    learning_rate: 0.1
    max_depth: 10
    subsample: 0.8
    random_state: 42
  
  ensemble:
    voting: "soft"
    weights: [0.6, 0.4]

# Feature Engineering
FEATURES:
  orbital_params: 
    - "semi_major_axis"
    - "eccentricity" 
    - "inclination"
    - "perihelion_distance"
    - "aphelion_distance"
  
  physical_params:
    - "absolute_magnitude"
    - "albedo"
    - "diameter"
    - "rotation_period"
  
  spectral_params:
    - "spectral_type"
    - "taxonomic_class"
    - "slope_parameter"

# Data Processing
DATA_PROCESSING:
  max_api_calls_per_minute: 100
  cache_expiry_days: 7
  batch_size: 50
  
# Training Configuration
TRAINING:
  test_size: 0.2
  validation_size: 0.2
  random_state: 42
  stratify: true
  cross_validation_folds: 5

# Logging
LOGGING:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_dir: "logs"
